routes/web.php
<?php

use App\Http\Controllers\HomeComtroller;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NotesController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [HomeController::class, 'home'])->name('dashboard');


Route::resource('/notes', 'App\Http\Controllers\NotesController');
Route::post('/notes/toggle-status/{note}', [NotesController::class, 'toggleStatus'])->middleware(['auth']);
Route::post('/notes/{note}/comment', [NotesController::class, 'comment'])->middleware(['auth']);

require __DIR__ . '/auth.php';

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    use HasFactory;

    protected $fillable = ['text', 'note_id', 'user_id'];
}

app/Models/Note.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    use HasFactory;

    protected $fillable = ['text', 'published', 'user_id', 'slug'];

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function comments()
    {
        return $this->hasMany('App\Models\Comment');
    }

    public function scopeIsPublished($query)
    {
        return $query->where('published', '1');
    }

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Note;

class HomeController extends Controller
{
    public function home()
    {
        $notes = Note::with('user')->inRandomOrder()->isPublished()->get();
        return view('notes/all', compact('notes'));
    }
}

app/Http/Controllers/NotesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CommentRequest;
use App\Http\Requests\NoteRequest;
use App\Models\Note;
use Carbon\Carbon;
use Illuminate\Support\Str;

class NotesController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth'])->except(['show']);
    }

    public function index()
    {
        $notes = Note::where('user_id', auth()->id())->get();
        return view('notes/my-notes', compact('notes'));
    }

    public function create()
    {
        return view('notes/add');
    }

    public function store(NoteRequest $request)
    {
        $data = $request->validated();
        $data['published'] = $data['published'] == 'on';
        $data['slug'] = Str::slug(Str::words($data['text'] . "-" , 5). Carbon::now()->timestamp);
        Note::create($data + ['user_id' => auth()->id()]);
        return redirect('/notes');
    }

    public function destroy(Note $note)
    {
        $note->delete();
        return response()->json(['message' => 'Successfully Deleted']);
    }

    public function show(Note $note)
    {
        if (!$note->published)
            $this->authorize('show', [$note]);
        $note = Note::with('comments')->where('slug', $note->slug)->firstOrFail();
        return view('notes/show', compact('note'));
    }

    public function toggleStatus(Note $note)
    {
        $this->authorize('toggleStatus', [$note]);
        $note->published = !$note->published;
        $note->save();
        return response()->json(['message' => 'Operation Done Successfully']);
    }

    public function comment(Note $note, CommentRequest $request)
    {
        $data = $request->validated();
        $data['user_id'] = auth()->id();
        $note->comments()->create($data);
        return response()->json(['message' => 'Commented Successfully', 'text' => $data['text']]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>

        @stack('styles')
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    @stack('scripts')
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex-shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600"/>
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    @auth
                        <x-nav-link :href="route('notes.index')" :active="request()->routeIs('notes.index')">
                            {{ __('My Notes') }}
                        </x-nav-link>
                    @endauth
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Notes') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            @auth
                <div class="hidden sm:flex sm:items-center sm:ml-6">
                    <x-dropdown align="right" width="48">
                        <x-slot name="trigger">
                            <button
                                class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                                <div>{{ Auth::user()->name }}</div>

                                <div class="ml-1">
                                    <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg"
                                         viewBox="0 0 20 20">
                                        <path fill-rule="evenodd"
                                              d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                                              clip-rule="evenodd"/>
                                    </svg>
                                </div>
                            </button>
                        </x-slot>

                        <x-slot name="content">
                            <!-- Authentication -->
                            <x-dropdown-link :href="route('notes.index')">
                                {{ __('My Notes') }}
                            </x-dropdown-link>
                            <x-dropdown-link :href="route('notes.create')">
                                {{ __('Add Note') }}
                            </x-dropdown-link>
                            <form method="POST" action="{{ route('logout') }}">
                                @csrf

                                <x-dropdown-link :href="route('logout')"
                                                 onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                    {{ __('Log out') }}
                                </x-dropdown-link>
                            </form>
                        </x-slot>
                    </x-dropdown>
                </div>
            @else
                <div class="sm:flex sm:items-center sm:ml-6">
                    <x-nav-link :href="route('login')" :active="request()->routeIs('login')">
                        {{ __('Log in') }}
                    </x-nav-link>

                    @if (Route::has('register'))
                        <x-nav-link :href="route('register')" :active="request()->routeIs('register')">
                            {{ __('Register') }}
                        </x-nav-link>
                    @endif
                </div>
        @endauth

        <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open"
                        class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex"
                              stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M4 6h16M4 12h16M4 18h16"/>
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round"
                              stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        @auth
            <div class="pt-4 pb-1 border-t border-gray-200">
                <div class="flex items-center px-4">
                    <div class="flex-shrink-0">
                        <svg class="h-10 w-10 fill-current text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none"
                             viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/>
                        </svg>
                    </div>

                    <div class="ml-3">
                        <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                        <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
                    </div>
                </div>

                <div class="mt-3 space-y-1">
                    <!-- Authentication -->
                    <form method="POST" action="{{ route('logout') }}">
                        @csrf

                        <x-responsive-nav-link :href="route('logout')"
                                               onclick="event.preventDefault();
                                        this.closest('form').submit();">
                            {{ __('Log out') }}
                        </x-responsive-nav-link>
                    </form>
                </div>
            </div>
        @endauth
    </div>
</nav>

resources/views/notes/add.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Add Note') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <form action="{{route('notes.store')}}" enctype="multipart/form-data" method="post"
                      class="p-6 bg-white border-b border-gray-200">
                    @csrf
                    <div>
                        <textarea name="text" class="border p-2 mt-3 w-full rounded" rows="10">{{old('text')}}</textarea>
                        @if ($errors->has('text'))
                            <small class="text-sm text-red-500">{{$errors->first('text')}}</small>
                        @endif
                    </div>
                    <div class="flex space-x-2 mt-2">
                        <input type="hidden" name="published" value="off">
                        <input type="checkbox" name="published" id="is-published" class="inline-block">
                        <label for="is-published" class="text-gray-600 text-sm">Is Published?</label>
                    </div>
                    @if ($errors->has('published'))
                        <small class="text-sm text-red-500">{{$errors->first('published')}}</small>
                    @endif
                    <div class="flex items-center justify-end mt-4">

                        <x-button type="submit" class="ml-3">
                            {{ __('Submit') }}
                        </x-button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/notes/all.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Notes') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="flex flex-wrap">
                @foreach($notes as $note)
                    <div class="px-2 mb-3 w-full sm:w-1/2 ">
                        <a target="_blank" href="{{route('notes.show',$note->slug)}}"
                           class="bg-white transition hover:bg-gray-50 shadow-sm rounded-lg cursor-pointer block">
                            <p class="py-6 px-3 border-b border-gray-200">
                                {{\Illuminate\Support\Str::words($note->text,8)}}
                            </p>
                            <span class="py-1 px-3 block text-sm">By <span
                                    class="text-blue-400">{{$note->user->name}}</span></span>
                        </a>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/notes/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ \Illuminate\Support\Str::words($note->text,5) }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <p class="px-6 py-4">{!! $note->text !!}</p>
            </div>
        </div>
    </div>
    <div class="pb-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <h2 class="px-3 py-3 border-b bg-gray-50 font-semibold text-xl text-gray-800 leading-tight">
                    Comments
                </h2>
                <ul class="comment-list">
                    @foreach($note->comments as $comment)
                        <li class="px-4 py-4 border-b">{{$comment->text}}</li>
                    @endforeach
                    @auth
                        <li class="px-4 py-3 comment-form">
                            <form action="" class="flex items-center">
                                @csrf
                                <input type="text" name="text" placeholder="Write your comment here..." required
                                       class="w-10/12 flex-1 appearance-none rounded shadow p-3 text-grey-dark mr-2 focus:outline-none">
                                <button type="submit"
                                        class="w-2/12 appearance-none bg-gray-800 text-white text-base font-semibold tracking-wide uppercase p-3 rounded shadow hover:bg-gray-600 transition">
                                    Comment
                                </button>
                            </form>
                        </li>
                    @endauth
                </ul>
            </div>
        </div>
    </div>
    @push('styles')
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    @endpush
    @push('scripts')
        <script>
            $('.comment-form form').off('submit').on('submit', function ($event) {
                $event.preventDefault();
                let data = $(this).serialize();
                $.ajax({
                    type: 'post',
                    url: '{{route('notes.index')}}/' + '{{$note->slug}}/comment',
                    data,
                    success(res) {
                        $('.comment-form form input[type=text]').val('')
                        $('.comment-form').before(`<li class="px-4 py-3 border-b">${res.text}</li>`)
                    }
                })
            })
        </script>
    @endpush
</x-app-layout>